### ISSUE TITLE
Does it really work as PWA app? after install on "PWA" on iphone xr, header disappeared and can't click on anything clickable. 

### ISSUE THREAD

**Issue by mobilelifeful** [hbstack/pwa#75]
Does it really work as PWA app? after install on "PWA" on iphone xr, header disappeared and can't click on anything clickable.  Thank you.

**Comment by razonyang** [comment]
https://github.com/hbstack/pwa/assets/17720932/0b834e33-b43c-4289-8f89-9add1b7556f3

Just tested, works as expected when installing via FireFox on theme.hbstack.dev. I guess the installation wasn't completed on your side, but there isn't enough info to check. What site do you test? Does the site work on when install via FireFox?

Btw, the header will diappear when scrolling down, and show up when scrolling up.

**Comment by razonyang** [comment]
Tested theme.hbstack.dev on iPhone XR via BrowserStack, works fine.

![image](https://github.com/hbstack/pwa/assets/17720932/7f1a9734-f480-4f47-99ff-8b1da5d96a7b)

**Comment by mobilelifeful** [comment]
the nav/header disappeared as the the "install on Ubuntu" for example. (any pages are the same). In order to for nav/header to be appear, we can scroll down a bit, then scroll up a bit, then the nav/header appeared with all the functions working.  

At the same time, if we want the nav/header appear on the page （as start reading the content from the top, can we hit the back to up button, which somehow the nav/header appear again)
Also for the nav/header to be appear, we can scroll down a bit, then scroll up a bit the nav/header appear）

Although with all these issues with the iphone xr,  they doesn't appear on ipad (the nav/header stays on top nicely).  not sure if ios version problem or my iphone xr problem.   

This doesn't seem to be the issue of themes, will close the issue now.

**Comment by razonyang** [comment]
> While nav/header appear on ipad. but can't click on search or menu option.

I was able to reproduce it, the JS seems not working on Safari, will look into this this week.

**Comment by razonyang** [comment]
This issue happened on old Safari browsers, I've tested it on iPad and iPhone XR on browserstack, according the test result, the theme works on iOS v15 and iOS v16. There is no plan to support older browsers, so I'm closing it for now.
